### ISSUE TITLE
Accept Changes for Providence

### ISSUE THREAD

**Issue by theryankelly** [codeisland/open-data-census#22]
We need a working account that can accept changes for Providence (http://us-city.census.okfn.org/place/providence)

**Comment by theryankelly** [comment]
My email address rkelly@codeforamerica.org is a working admin or "librarian" for providence

**Comment by theryankelly** [comment]
I am now able to accept changes! We moved up to #26 thank to edits by @SLarrick and @jonbittner

**Comment by goldenmeanie** [comment]
Woooo!
